### ISSUE TITLE
GitHub workflow not working

### ISSUE THREAD

**Issue by dnsos** [technologiestiftung/berlin-iot-hub-frontend#1]
Even though there is a `.github/workflows/build.yml` file, GitHub doesn't pick it up for its Actions.

@fabianmoronzirfas do you happen to know why this is?

**Comment by ff6347** [comment]
The name "master" for the default branch is deprecated and will be changed on all of GitHub to default to "main". Since the master and slave terminology is pretty gross I already changed it as our default. Sorry for that.

You can change your local default setting by running the following command.

```bash
git config --global init.defaultBranch main
```
